15 восстановление пароля
piybeep/cargo-c pull request #21
Opened 2023-05-01 19:40 UTC by NAVIch0k

2023-05-03 11:11 UTC, danyatochkaru requested changes

2023-05-03 11:11 UTC, danyatochkaru commented on src/pages/recovery/index.tsx
> +import { GetPassword } from '@/modules/GetPassword'
настрой идексы, чтобы импорт был из `@/modules`

2023-05-03 16:24 UTC, NAVIch0k commented on src/pages/recovery/index.tsx
> +import { GetPassword } from '@/modules/GetPassword'
сделал

2023-05-04 11:31 UTC, danyatochkaru approved these changes

2023-05-04 11:31 UTC, merged